### ISSUE TITLE
rlwrap bails out when run in eshell (emacs shell)

### ISSUE THREAD

**Issue by hanslub42** [hanslub42/rlwrap#1]
eshell runs commands under a terminal (pty) with winsize.ws_col (width) == 0
At present, rlwrap bails out in such a case. Shouldn't it get out of the way and just exec the slave command ?

**Comment by philemonphonon** [comment]
Hi Hans,
I get this message in an Emacs Shell (M-x shell, not eshell) when launching software that use rlwrap under the hood in their shell scripts (e.g. maxima, cast3m...) :
rlwrap: error: My terminal reports width=0 (is it emacs?)  I can't handle this, sorry!

This is with rlwrap 0.41. It behaves nicer than previous version that would segfault in this case...

What I usually do is make my own version of the incriminated shell script that does not use rlwrap when Emacs is detected using one of the environment variables that Emacs sets in subshells. This not a nice hack because the original shell script may change over time.

This why I agree with your comment that in such cases rlwrap just "should get out of the way and just exec the slave command" as emacs shell or eshell have their own mechanism to take care of command history, completion, etc... 

Keep up the good work with rlwrap! It's very nice to have when there is no Emacs shell in sight :)

**Comment by hanslub42** [comment]
`rlwrap` now just execs the slave command whenever  `INSIDE_EMACS` is set in the environment.
