### ISSUE TITLE
--history-no-dupes 2 gives unexpected results

### ISSUE THREAD

**Issue by nkh** [hanslub42/rlwrap#154]
command:  order=$(rlwrap --history-no-dupes 2 -pYellow -S 'Your pizza? ' -H past_orders -P Margherita -o ./silent)

past_orders file contents:
Margheritarlökmefref
Margherita
Margheritaxxx
Margherita
Margheritaxxx
Margherita

I expected the history to  be like listing below when n is 2
Margheritarlökmefref
Margheritaxxx
Margherita

**Comment by hanslub42** [comment]
`--history-no-dupes 2` only influences what is put in the history file _for the current session_. It does not rewrite history

I agree that the manual suggests otherwise:

>  n = 2 will make `rlwrap` drop  all  previous  occurrences of the current input from the list.

I prefer the current behaviour as less intrusive (is wouldn't be difficult to write a [script to sanitise](https://stackoverflow.com/questions/46790661/how-to-keep-the-last-occurrence-of-duplicate-lines-in-a-text-file)  your duplicate-ridden history file)

I'll mark this as a "manpage bug"

**Comment by hanslub42** [comment]
I cannot reproduce. This is what I see:

```shell
$ order=$(rlwrap -pYellow -S 'Your pizza? ' -H past_orders -P Margherita -o cat)
Your pizza? AB CD E # this remains on screen after pressing ENTER
$ echo $order
AB CD E
$ order=$(rlwrap -pYellow -S 'Your pizza? ' -H past_orders -P Margherita -o cat)
Your pizza? AB CD E #after pressing the up arrow once
```

**Comment by hanslub42** [comment]
Clarified this in manpage (see 9d6d5f1d3bdccc3144cc076ad7335e06326da4b9)
