### ISSUE TITLE
problems completing filenames that contain hyphens

### ISSUE THREAD

**Issue by arekolek** [hanslub42/rlwrap#37]
Tested with `rlwrap 0.37` and `gnuplot 4.6 patchlevel 4` on `Ubuntu 14.04.3`.

Seems like there needs to be at least two files with a common prefix and a hyphen in a directory for this to occur.

To reproduce the problem first set up some test files:

    $ mkdir test
    $ cd test
    $ touch test-a.txt test-b.txt

Now try file completion with rlwrap:

    $ rlwrap -a -c gnuplot
    gnuplot> t[TAB]
    gnuplot> test-[TAB]
    gnuplot> test-test-[TAB]
    gnuplot> test-test-test-[TAB]

Let's rewind and try:

    gnuplot> test-a[TAB]

Nothing happens.

But it all works fine with gnuplot's built-in readline support:

    gnuplot> t[TAB]
    gnuplot> test-[TAB]
    test-a.txt test-b.txt
    gnuplot> test-a[TAB]
    gnuplot> test-a.txt 

If there are other files, something else happens, so add one:

    $ touch not-a-test.txt

This is what happens with rlwrap:

    gnuplot> t[TAB]
    gnuplot> test-[TAB]
    not-a-test.txt  test-a.txt      test-b.txt      
    gnuplot> test-a[TAB]

Then nothing happens after pressing [TAB], no matter how many more characters of the filename I type myself.

Again, this is how it should look like and how it works in gnuplot:

    gnuplot> t[TAB]
    gnuplot> test-[TAB]
    test-a.txt test-b.txt
    gnuplot> test-a[TAB]
    gnuplot> test-a.txt

**Comment by hanslub42** [comment]
This issue comes up every now and then. By default, `rlwrap` considers `'` and `-` (apostrophe and hyphen) *word-breaking*, which means that it will not consider filenames which contain those characters as valid completions (you will obeserve something like that in `bash` or `zsh` when you encounter filenames with spaces.

Calling `rlwrap` with  `--break-chars=""` (or simpler: `-b ''`) will convince  it that only whitespace is word-breaking, after which it should behave as you expect.

All this poses two questions:

- should the manpage be clearer on this?
- should `rlwrap` use the same word-breakers for filename completion as it does for keyword completion?

**Comment by arekolek** [comment]
This solves the problem, indeed. Using `-b \'` also solves the issue mentioned in [this comment on stackoverflow](http://stackoverflow.com/questions/16492560/history-auto-complete-in-gnuplot/33009764?noredirect=1#comment54018128_33009764).

If the description of the `-c` option in the manpage mentioned other options (like `-b`) that can affect its behavior, then yes, it would save me from falling for this one.

As for the second question, I can't really say as I'm not aware what word-breaking rules are used for keyword completion.
