### ISSUE TITLE
Context-aware completion

### ISSUE THREAD

**Issue by mklm** [hanslub42/rlwrap#81]
Hi and thanks for your work on rlwrap,

I would appreciate a context-aware completion. In particular, while in string-context (inside double quotes for most languages) I find file completion more appriopriate and useful.

Cheers.

**Comment by hanslub42** [comment]
`rlwrap` allows one to write filters (in `perl` or `python3`) to accomplish this. Have a look at the `RlwrapFilter (3)` manpage.

More specifically, the `completion_handler` method of the `RlwrapFilter` object gets called with  three arguments: the entire input line, the prefix (partial word to complete), and `rlwrap`s   own completion list.  It should return a (possibly revised) list of completions.  

As an example, suppose the user has typed `Let's open the file called "blah<TAB>`. The handler will be called like this (in pseudocode)

                filter_object.myhandler("Let's open the file called \"blah", "\"blah", "blahblah")

Your filter script should notice the odd number of double quotes in the first argument, get a list of files in `rlwrap`s current working directory (via the `filter_object.cwd()` method), weed out the non-completions and return the remainder.

I added the filter mechanism to `rlwrap` because it is already quite spaghetti-like after 20+ years, and I wanted to prevent feature creep.
