### ISSUE TITLE
An interesting issue handling multi-bytes characters

### ISSUE THREAD

**Issue by greenlaw110** [hanslub42/rlwrap#98]
Refer to https://github.com/actframework/actframework/issues/1213

When use [nc](https://linux.die.net/man/1/nc) directly:
![0](https://user-images.githubusercontent.com/216930/66167197-cfe90980-e67c-11e9-98b0-fd45e8c94801.gif)

Using `nc` with `rlwrap`:
![0](https://user-images.githubusercontent.com/216930/66167272-01fa6b80-e67d-11e9-9e55-c0cb1e7282a9.gif)

It looks to me that rlwrap isn't counting the column width correctly for muti-bytes chars

**Comment by greenlaw110** [comment]
I have created a project to help reproduce this issue:

https://github.com/greenlaw110/rlwrap-issue

**Comment by hanslub42** [comment]
This has been high on my to-do list for some time. `rlwrap` still uses `strlen()` instead of `wcslen()`  to determine how wide a string will when displayed on your terminal, which yields an incorrect result  when a multibyte character is displayed in one character cell in your locale.

My day job takes all my time at the moment, so this may take some time (this is a non-trivial project, simply replacing `strlen` by `wcslen` won't do the job)

**Comment by hanslub42** [comment]
This should be fixed by 46aaddab7ac6355ad7a8ff1a698e9f23d3dfb02d
